title: "R++"
author: "Rohit Menon"
description: "Musings of a random software engineer"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true               # show a sidebar instead of the usual header
show_excerpts: true         # show article excerpts on the home page
show_related: true          # show the previous and next links after every post
show_description: true      # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling

dark_header: true            # always keep the header dark
minimal: false               # use simpler style

# Pagination settings

paginate: 5
paginate_path: "/page:num/"
excerpt_separator: <!--more-->

# Menu

navigation:
  - {file: "about.md", icon: info, title: "About"}
  - {file: "index.html", icon: blog, title: Blog}

external:                    # see http://fontawesome.com/icons
  - {title: Twitter, icon: twitter, url: "https://twitter.com/rohitsm"}
  - {title: Github, icon: github, url: "https://github.com/rohitsm"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/rohitsm"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-gist
 - jekyll-paginate

